### PR TITLE
Port to Edge

### PR DESCRIPTION
**Pull request by 999eagle**
Tested on Chrome and Edge, it works on both now.

### CODE REVIEW

**Comment by 999eagle** [comment]
@Onestay would you mind if I published CR-Unblocker for Edge in the Windows Store under my name?

**Comment by Onestay** [comment]
Sure, you can. I would just appreciate some credits.

**Comment by 999eagle** [comment]
Ok, I've tested this code in Firefox, Chrome and Edge, it works in all 3 browsers correctly as far as I can tell.

**Comment by Onestay** [comment]
I'm currently really busy and don't have time to look into this. But once I have time I'll test it and merge it.

**Comment by Onestay** [comment]
Hey, would it be okay if I do not merge this since I want this repo to be for the chrome extension only? I will obviously put the edge link into the ReadMe. However feel free to create your own repo with the code. You can link to it via the readme aswell :)

**Comment by 999eagle** [comment]
Alright, I'll keep my own repo of this extension and link to your repo. Thanks for allowing me to do this :)

**Pull request closed without merging**
